#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InvoiceMaker.Resource", IsApplication=true)]

namespace InvoiceMaker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::cbforestsharp.Droid.Resource.String.library_name = global::InvoiceMaker.Resource.String.library_name;
			global::Couchbase.Lite.Android.Resource.String.library_name = global::InvoiceMaker.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_example = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_example = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_example = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_example = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_example = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_example = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_example = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_example = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_focused_example = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pressed_example = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_example = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_example = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int example_btn_default_disabled_focused_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int example_btn_default_disabled_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int example_btn_default_focused_holo_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int example_btn_default_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int example_btn_default_normal_holo_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int example_btn_default_pressed_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_close = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_new = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int list_focused_example = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int list_pressed_example = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int menu_dropdown_panel_example = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int progress_bg_example = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int progress_horizontal_example = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int progress_primary_example = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int progress_secondary_example = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int selectable_background_example = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_ab_default_example = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_disabled_example = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_focused_example = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_ab_pressed_example = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int spinner_background_ab_example = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_indicator_ab_example = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_selected_example = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_selected_focused_example = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_selected_pressed_example = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_unselected_example = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_unselected_focused_example = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_unselected_pressed_example = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080010
			public const int actionClose = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int actionNew = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int buttonConfirm = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int buttonCreateInvoice = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int editTextAnzahl = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int editTextDatum = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int editTextFirma = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int editTextNummer = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int editTextPreis = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int editTextProdukt = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int editTextStrasseOrt = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout2 = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout3 = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout4 = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int myButton = 2131230720;
			
			// aapt resource value: 0x7f08000e
			public const int webViewRechnung = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int NewInvoice = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int InvoiceMakerMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int icon = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int newInvoice = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBar_Solid_Example = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_Transparent_Example = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ActionBarTabStyle_Example = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ActionButton_CloseMode_Example = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ButtonExample_Example = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int DropDownListView_Example = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int DropDownNav_Example = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int PopupMenu_Example = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ProgressBar_Example = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Example = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int Theme_Example_Widget = 2131099658;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
